---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: cryptocom/chain-test:latest
  pull: if-not-exists
  commands:
  - export CARGO_HOME=$PWD/drone/cargo
  - export CARGO_TARGET_DIR=$PWD/drone/target
  - export PATH=$CARGO_HOME/bin:$PATH
  - ./docker/build.sh

- name: unit-tests
  image: cryptocom/chain-test:latest
  pull: if-not-exists
  commands:
  - export CARGO_HOME=$PWD/drone/cargo
  - export CARGO_TARGET_DIR=$PWD/drone/target
  - export CRYPTO_CHAIN_ENABLE_SANITY_CHECKS=1
  - cargo test

- name: integration-tests
  image: cryptocom/chain-test:latest
  pull: if-not-exists
  privileged: true
  volumes:
  - name: sgx
    path: /dev/isgx
  environment:
    SPID:
      from_secret: SPID
    IAS_API_KEY:
      from_secret: IAS_API_KEY
  commands:
  - export CARGO_HOME=$PWD/drone/cargo
  - export CARGO_TARGET_DIR=$PWD/drone/target
  - export PATH=$CARGO_HOME/bin:$PATH
  - export PYTHON_VENV_DIR=$PWD/drone/venv
  - export CRYPTO_CHAIN_ENABLE_SANITY_CHECKS=1
  - LD_LIBRARY_PATH=/opt/intel/sgx-aesm-service/aesm /opt/intel/sgx-aesm-service/aesm/aesm_service --no-daemon &
  - ./integration-tests/run.sh

- name: multinode-tests
  image: cryptocom/chain-test:latest
  pull: if-not-exists
  privileged: true
  volumes:
  - name: sgx
    path: /dev/isgx
  environment:
    SPID:
      from_secret: SPID
    IAS_API_KEY:
      from_secret: IAS_API_KEY
  commands:
  - export CARGO_HOME=$PWD/drone/cargo
  - export CARGO_TARGET_DIR=$PWD/drone/target
  - export PATH=$CARGO_HOME/bin:$PATH
  - export PYTHON_VENV_DIR=$PWD/drone/venv
  - export CRYPTO_CHAIN_ENABLE_SANITY_CHECKS=1
  - LD_LIBRARY_PATH=/opt/intel/sgx-aesm-service/aesm /opt/intel/sgx-aesm-service/aesm/aesm_service --no-daemon &
  - ./integration-tests/run_multinode.sh

- name: sgx-test
  image: cryptocom/chain-test:latest
  pull: if-not-exists
  privileged: true
  volumes:
  - name: sgx
    path: /dev/isgx
  environment:
    SGX_TEST: 1
    RUST_LOG: debug
  commands:
  - export CARGO_HOME=$PWD/drone/cargo
  - export CARGO_TARGET_DIR=/tmp
  - LD_LIBRARY_PATH=/opt/intel/sgx-aesm-service/aesm /opt/intel/sgx-aesm-service/aesm/aesm_service --no-daemon &
  - make -C chain-tx-enclave/tx-validation
  - cargo build --no-default-features --features sgx-test --manifest-path chain-abci/Cargo.toml
  - cd $CARGO_TARGET_DIR/debug
  - ./chain-abci

- name: teardown
  image: cryptocom/chain-test:latest
  pull: if-not-exists
  commands:
  - ./integration-tests/cleanup.sh
  when:
    status:
      - success
      - failure

volumes:
  - name: sgx
    host:
      path: /dev/isgx

trigger:
  branch:
  - master
  - staging
  - trying
  event:
  - push

---
kind: pipeline
name: fuzzer

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: cryptocom/fuzzer:latest
  pull: if-not-exists
  environment:
    FUZZIT_API_KEY:
      from_secret: FUZZIT_API_KEY
  commands:
  - ./ci-scripts/fuzzit.sh

trigger:
  branch:
  - master
  event:
  - push
      

---
kind: signature
hmac: 3dce97b3e6be0fc210afbdb02e08038d0b64ee09ce8d3af530dddf29770ea00a

...
