---
kind: pipeline
name: rust

steps:
- name: Build and Test
  image: chain
  pull: never
  commands:
  - export RUST_BACKTRACE=1
  - export RUSTFLAGS=-Ctarget-feature=+aes,+sse2,+sse4.1,+ssse3
  - export LD_LIBRARY_PATH=$HOME/lib
  - export LIBRARY_PATH=$HOME/lib
  - export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
  - export PKG_CONFIG_PATH=$HOME/lib/pkgconfig
  - cargo build
  - cargo test
  - echo "HOME FOLDER = " $HOME

---
kind: pipeline
type: exec
name: integration-tests

platform:
  os: linux
  arch: amd64

steps:
- name: Build and Test
  commands:
  - mkdir bin
  - export PATH="$PATH:$PWD/bin"
  - curl -sSL "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o bin/docker-compose
  - chmod +x bin/docker-compose
  - export NIX_REMOTE=daemon
  - export PATH="$PATH:/nix/var/nix/profiles/default/bin/"
  - export DOCKER_COMPOSE_PREFIX="${DRONE_BRANCH}"
  - . /usr/local/etc/profile.d/nix.sh
  - . /opt/intel/sgxsdk/sgxsdk/environment
  # - nix-channel --add https://nixos.org/channels/nixpkgs-unstable
  # - nix-channel --update
  - nix-shell ci-scripts/drone.nix --run "./ci-scripts/run-integration-tests.sh"
- name: Teardown
  commands:
  - export PATH="$PATH:$PWD/bin"
  - cd integration-tests
  - docker-compose -p "${DRONE_BRANCH}" down || exit 0
  when:
    status:
      - success
      - failure

trigger:
  branch:
  - master
  - staging
  - trying
  event:
  - push

---
kind: pipeline
type: exec
name: sgx-cargo-1804-hw1

platform:
  os: linux
  arch: amd64

steps:
- name: Build and Test
  commands:
  - export SGX_MODE=HW
  - export NETWORK_ID=ab
  - . /opt/intel/sgxsdk/sgxsdk/environment
  - rustup default nightly-2019-08-01-x86_64-unknown-linux-gnu
  - ls -l /dev/sgx
  - ls -l /var/run/aesmd/aesm.socket
  - cd chain-tx-enclave/tx-validation && make clean && SGX_TEST=1 make
  - cd bin && sh -c 'echo $$$ > $HOME/.PID; exec ./tx-validation-app'
- name: Teardown
  commands:
  - kill "$(cat "$HOME/.PID")" || echo "./tx-validation-app already exited"
  - (ps | grep ./tx-validation-app) || exit 0
  when:
    status:
      - success
      - failure

trigger:
  branch:
  - master
  - staging
  - trying
  event:
  - push

---
kind: pipeline
type: exec
name: sgx-cargo-1804-hw2

platform:
  os: linux
  arch: amd64

steps:
- name: Build and Test
  environment:
    SPID:
      from_secret: dev_spid
    IAS_API_KEY:
      from_secret: dev_ias_key
  commands:
  - export RUST_BACKTRACE=1
  - export RUSTFLAGS=-Ctarget-feature=+aes,+sse2,+sse4.1,+ssse3
  - export SGX_MODE=HW
  - export NETWORK_ID=ab
  - export RUST_LOG=info
  - export TX_VALIDATION_BIN_DIR=`pwd`/chain-tx-enclave/tx-validation/bin/
  - export TX_QUERY_APP_PORT=`./ci-scripts/find-free-port.sh`
  - . /opt/intel/sgxsdk/sgxsdk/environment
  - rustup default nightly-2019-08-01-x86_64-unknown-linux-gnu
  - ls -l /dev/sgx
  - ls -l /var/run/aesmd/aesm.socket
  - cd chain-tx-enclave/tx-validation && make clean && make
  - cd ../tx-query && make clean && SGX_TEST=1 make
  - cd bin && sh -c 'echo $$$ > $HOME/.PID; exec ./tx-query-app'
- name: Teardown
  commands:
  - kill "$(cat "$HOME/.PID")" || echo "./tx-query-app already exited"
  - (ps | grep ./tx-query-app) || exit 0
  when:
    status:
      - success
      - failure

trigger:
  branch:
  - master
  - staging
  - trying
  event:
  - push


---
kind: pipeline
type: exec
name: integration-tests-jail-unjail

platform:
  os: linux
  arch: amd64

steps:
- name: integration-tests
  commands:
  - mkdir bin
  - export PATH="$PATH:$PWD/bin"
  - echo "OK"
  - cd integration-tests/jail
  - ./run.sh


---
kind: signature
hmac: cf4d1c1fdb5895f7fa7bcf7edb0e1fe4131cf8d9d548a46cb8f4aca4e182d4ab

...
