---
kind: pipeline
type: exec
name: integration-tests-jail-unjail

platform:
  os: linux
  arch: amd64

steps:
- name: integration-tests
  commands:
  - cd integration-tests/all
  - ./run.sh
- name: teardown
  commands:
  - cd integration-tests/jail
  - ./shutdown.sh
  when:
    status:
     - success
     - failure



