rust: &rust
  language: rust
  sudo: required
  dist: trusty
  addons:
    apt:
      packages:
        - git
        - libssl-dev
        - libcurl4-openssl-dev
        - libelf-dev
        - libdw-dev
        - cmake
        - gcc
        - binutils-dev
        - libc6-dev
  cache:
    directories:
      - /home/travis/.cargo

  before_cache:
    - rm -rf /home/travis/.cargo/registry

  env:
    - RUST_BACKTRACE=1
    - RUSTFLAGS=-Ctarget-feature=+aes,+ssse3
    - PATH=$HOME/.local/bin:$PATH
    - LD_LIBRARY_PATH=/home/travis/lib
    - LIBRARY_PATH=/home/travis/lib
    - PKG_CONFIG_PATH=/home/travis/lib/pkgconfig
  before_install: # versions from https://github.com/erickt/rust-zmq/blob/master/.travis.yml
    - git clone https://github.com/leejw51crypto/ChainTravis.git /home/travis/tmpdir
    - cp -Rf /home/travis/tmpdir/* /home/travis

  script:
    - cargo build
    - cargo test
    - |
      if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
        (rustfmt --version || rustup component add rustfmt) &&
        cargo fmt -- --check --color=auto &&
        (cargo-clippy --version || rustup component add clippy) &&
        cargo clippy -- -D warnings &&
        (cargo-audit -h || cargo install cargo-audit) &&
        cargo audit       
      fi

  after_success: |
    if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
      sudo cp /home/travis/bin/kcov  /usr/local/bin/
      sudo cp /home/travis/bin/kcov-system-daemon  /usr/local/bin/
      echo "kcov is successfully installed"
      cargo-kcov --version || cargo install cargo-kcov;
      travis_wait 30 cargo kcov --all;
      bash <(curl -s https://codecov.io/bash);
    fi

jobs:
  allow_failures:
    - rust: nightly
  include:
    - <<: *rust
      rust: stable
      if: (branch != staging.tmp) AND (branch != trying.tmp)
    - <<: *rust
      rust: beta
      if: (branch = staging) OR (branch = trying)
    - <<: *rust
      rust: nightly
      if: (branch != staging.tmp) AND (branch != trying.tmp)
    - name: Integration Test
      language: rust
      sudo: required
      dist: trusty
      if: (branch = staging) OR (branch = trying)
      addons:
        apt:
          packages:
            - git
            - libssl-dev
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - gcc
            - binutils-dev
            - libc6-dev
      cache:
        directories:
          - /home/travis/.cargo

      before_cache:
        - rm -rf /home/travis/.cargo/registry
      env:
        - RUSTFLAGS=-Ctarget-feature=+aes,+ssse3
        - PATH=$HOME/.local/bin:$PATH
        - LD_LIBRARY_PATH=/home/travis/lib
        - LIBRARY_PATH=/home/travis/lib
        - PKG_CONFIG_PATH=/home/travis/lib/pkgconfig
      before_install: # versions from https://github.com/erickt/rust-zmq/blob/master/.travis.yml
        - |
          git clone https://github.com/leejw51crypto/ChainTravis.git /home/travis/tmpdir
          cp -Rf /home/travis/tmpdir/* /home/travis
        - nvm install 10
        - |
          sudo cp integration-tests/docker/wait-for-it.sh /usr/local/bin
          sudo chmod +x /usr/local/bin/wait-for-it.sh
      script:
        - cd integration-tests
        - ./prepare.sh || travis_terminate 1;
        - . ./env.sh
        - docker-compose up -d || travis_terminate 1;
        - |
          sleep 25
          docker-compose ps
          docker-compose logs -t --tail="all"
        - ./run-test.sh || travis_terminate 1;
        - |
          cd client-rpc
          yarn
          yarn test
        - |
          docker-compose ps
          docker-compose logs -t --tail="all" || travis_terminate 0;
