[workspace]

members = [
    "chain-core",
    "chain-storage",
    "client-cli",
    "client-common",
    "client-core",
    "client-network",
    "client-rpc",
    "test-common",
    "dev-utils",
    "cro-clib",
]

