[package]
name = "cro-wasmlib"
version = "0.1.0"
authors = ["jongwhan lee <jonghwan@crypto.com>"]
edition = "2018"

[lib]
#crate-type = ["cdylib", "rlib"]
crate-type = ["staticlib"]


[dependencies]
wasm-bindgen = "0.2.63"
chain-core = { path = "../chain-core" }

