[package]
name = "client-rpc"
version = "0.1.0"
authors = ["Calvin Lau <calvin@crypto.com>"]
edition = "2018"

[dependencies]
dirs = "2.0.2"
chain-tx-filter = { path = "../chain-tx-filter" }
chain-core = { path = "../chain-core" }
client-common = { path = "../client-common" }
client-core = { path = "../client-core" }
client-network = { path= "../client-network"}
serde_json = "1.0.41"
jsonrpc-http-server = "13.2"
jsonrpc-core = "13.2"
jsonrpc-core-client = "13.2"
jsonrpc-derive = "13.2"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
chrono = { version = "0.4", features = ["serde"] }
hex = "0.4.0"
secstr = { version = "0.3.2", features = ["serde"] }
env_logger="0.7.0"
log ="0.4.8"

[dev-dependencies]
parity-scale-codec = "1.0"
